version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  api:
    # build:
    #   dockerfile: Dockerfile
    #   context: ./server
    image: 'rimpigarg/nagp-server:latest'
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    ports:
      - 1000:5000
    restart: always
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
