apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server-replicaset-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: server-replicaset
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10